version: 2

models:
  - name: stg_pokemons_abilities
    description: >
      Staging model representing the mapping between Pokémon and their abilities.
      Each row links a Pokémon to an ability, and includes English descriptions of the ability's effect.
    columns:
      - name: pokemon_id
        description: >
          Foreign key to `stg_pokemons_pokemon.pokemon_id`, representing the Pokémon who has this ability.
        meta:
          foreign_key:
            table: ref('stg_pokemons_pokemon')
            field: pokemon_id
      - name: ability_id
        description: >
          Identifier for the ability.
          Unique across all abilities.
      - name: ability_name
        description: >
          Canonical name of the ability in lowercase (e.g., "chlorophyll").
      - name: ability_effects
        description: >
          English-language description of what this ability does in battle or context.

  - name: stg_pokemons_characteristics
    description: >
      Staging model for Pokémon characteristics. These are flavor descriptions determined by the highest IV stat
      a Pokémon has. Each characteristic refers to a stat name (like "speed", "attack", etc.), and is mapped
      to a description such as "Likes to run" or "Proud of its power".
    columns:
      - name: characteristic_id
        description: Unique identifier for the characteristic.
      - name: stat_name
        description: >
          Name of the stat associated with this characteristic (e.g., 'attack', 'speed').
          Semantically links to Pokémon stats and is joinable via `stg_pokemons_pokemon`.
      - name: move_damage_class__name
        description: Damage class of the move associated with the stat (e.g., physical, special).
      - name: description
        description: Natural language description of the characteristic.
        meta:
          example: "Proud of its power"

  - name: stg_pokemons_pokemon
    description: >
      Staging model for Pokémon core information, joined with stats. Each row represents
      a single (pokemon, stat) pair, including metadata like height, weight, and base experience.
    columns:
      - name: pokemon_id
        description: Unique identifier for the Pokémon.
      - name: name
        description: Name of the Pokémon in lowercase.
      - name: base_experience
        description: Base XP earned for defeating this Pokémon.
      - name: height
        description: Height in decimetres.
      - name: weight
        description: Weight in hectograms.
      - name: is_default
        description: Whether this is the default variety for the species.
      - name: species__name
        description: Name of the species this Pokémon belongs to.
      - name: species__url
        description: URL of the species resource — not used for joining.
      - name: cries__latest
        description: Path to the latest available cry audio for the Pokémon.
      - name: cries__legacy
        description: Path to the legacy cry audio.
      - name: location_area_encounters
        description: URL for retrieving encounter information.
      - name: _dlt_id
        description: DLT internal unique ID.
      - name: _dlt_load_id
        description: DLT load ID.
      - name: base_stat
        description: Base value for the associated stat.
      - name: stat__name
        description: >
          Name of the stat (e.g., "attack", "speed").
          Joinable to `stg_pokemons_characteristics.stat_name`.
        meta:
          foreign_key:
            table: ref('stg_pokemons_characteristics')
            field: stat_name