version: 2

models:
  - name: stg_abilities
    description: >
      Staging model for Pokémon abilities. Each ability represents a passive trait a Pokémon can have,
      such as Intimidate or Levitate. This staging model transforms and standardizes data related to
      abilities fetched from PokeAPI.
    columns:
      - name: ability_id
        description: Unique identifier for the ability, matching the PokeAPI's `id` field.
      - name: name
        description: English name of the ability, such as "chlorophyll" or "intimidate".
      - name: is_main_series
        description: Boolean flag indicating whether the ability is used in the mainline Pokémon games.
      - name: generation_id
        description: Foreign key linking to the generation in which this ability was introduced.
      - name: effect
        description: Short description of the ability's effect as presented in the game UI.
      - name: effect_detail
        description: Extended explanation of the ability's mechanics, often useful for semantic reasoning or tooltip expansion.

  - name: stg_characteristics
    description: >
      Staging model for Pokémon characteristics. Characteristics are nuanced summaries of a Pokémon's highest IV stat,
      such as “Likes to run” or “Proud of its power.” These descriptions are derived from internal stat calculations.
    columns:
      - name: characteristic_id
        description: Primary key for the characteristic, typically aligning with PokeAPI’s `id`.
      - name: highest_stat_id
        description: Foreign key referencing the Pokémon stat with the highest IV.
      - name: message
        description: Human-readable string that describes the characteristic (e.g., "Strong willed", "Somewhat vain").
      - name: possible_values
        description: Array or mapping of characteristic values tied to specific IV ranges or stat combinations.

  - name: stg_pokemon
    description: >
      Staging model for base Pokémon entity details. This model consolidates key identity and classification features 
      for each Pokémon species, enabling joins with types, abilities, stats, and evolutions.
    columns:
      - name: pokemon_id
        description: Unique identifier for the Pokémon species.
      - name: name
        description: Pokémon's name in English, e.g., "bulbasaur", "pikachu".
      - name: base_experience
        description: The amount of base experience gained for defeating this Pokémon.
      - name: height
        description: Height of the Pokémon in decimetres.
      - name: weight
        description: Weight of the Pokémon in hectograms.
      - name: is_default
        description: Indicates whether this Pokémon is the default variety for its species.
      - name: order
        description: Ordering ID for Pokémon; used for sorting Pokémon with respect to other Pokémon.
      - name: species_id
        description: Foreign key to Pokémon species (for mapping to evolutions or descriptive data).
